/**
 * Detekia Pro — Multi-page PDF report HTML template.
 * Same design system as the one-page report (generate-pdf.js).
 */

function esc(s) {
  return String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

const T = {
  fr: {
    cover: { title: 'RAPPORT GEO COMPLET', subtitle: 'AUDIT SITE MULTI-PAGES', confidential: 'Ce rapport est personnel et confidentiel' },
    exec: { label: 'Synthese executive', h1: 'Vue d\'ensemble du site', distribution: 'Distribution des scores', strengths: 'Forces transverses', weaknesses: 'Faiblesses transverses', summary: 'Synthese', pagesAnalyzed: 'pages analysees', avgScore: 'Score moyen', medianScore: 'Score median', low: 'Faible (0-49)', avg: 'Moyen (50-69)', good: 'Bon (70+)' },
    beelevenMini: { label: 'Accompagnement', h1: 'Besoin d\'aide pour implementer ce plan ?', text: 'Beeleven, l\'agence qui a cree Detekia, peut implementer les recommandations de ce rapport pour vous : audit approfondi, optimisations techniques, suivi mensuel des resultats.', cta: 'Discutons-en &rarr;', footer: 'beeleven.fr &middot; hello@detekia.fr' },
    context: { label: 'Contexte 2026' },
    citation: { label: 'Test de visibilite IA', h1: 'Test de visibilite IA consolide', queriesCite: 'requetes\ncitent votre site', cited: 'Cite', notCited: 'Non cite', bestOpp: 'Meilleure opportunite :', mainBlocker: 'Blocage principal :', generic: 'Generique', niche: 'Niche', longTail: 'Longue traine' },
    patterns: { label: 'Patterns detectes', h1: 'Patterns transverses identifies', critique: 'Critique', important: 'Important', mineur: 'Mineur', pagesAffected: 'pages concernees' },
    actionPlan: { label: 'Plan d\'action site', h1: 'Actions prioritaires consolidees', colPriority: 'Priorite', colAction: 'Action', colCriterion: 'Critere', colImpact: 'Impact', colEffort: 'Effort', colPages: 'Pages', pagesAffected: 'pages concernees' },
    perPage: { label: 'Detail par page', errorNote: 'Cette page n\'a pas pu etre analysee', topRecos: 'Top 3 recommandations' },
    methodology: { label: 'Methodologie', h1: 'Methodologie d\'analyse', text: 'Ce rapport est genere par analyse automatisee de chaque page via un service de scraping specialise et evaluation sur 8 criteres ponderes. Le critere Neutralite editoriale est evalue par intelligence artificielle. Le test de visibilite IA est realise par simulation de requetes. Les resultats varient selon le moteur IA et le moment du test.' },
    beelevenFull: { label: 'Aller plus loin', h1: 'Aller plus loin avec Beeleven', text: 'Vous avez le diagnostic complet de votre site. Beeleven, l\'agence qui a cree Detekia, peut implementer les recommandations pour vous : audit approfondi, optimisations techniques, suivi mensuel des resultats.', cta: 'Discutons-en &rarr;' },
    email: { subject: 'Votre rapport GEO complet Detekia est pret', headerLabel: 'RAPPORT GEO COMPLET — AUDIT SITE', topPriority: 'Priorite absolue', filename: 'rapport-geo-complet' },
  },
  en: {
    cover: { title: 'COMPLETE GEO REPORT', subtitle: 'MULTI-PAGE SITE AUDIT', confidential: 'This report is personal and confidential' },
    exec: { label: 'Executive Summary', h1: 'Site Overview', distribution: 'Score Distribution', strengths: 'Cross-page Strengths', weaknesses: 'Cross-page Weaknesses', summary: 'Summary', pagesAnalyzed: 'pages analyzed', avgScore: 'Average Score', medianScore: 'Median Score', low: 'Low (0-49)', avg: 'Average (50-69)', good: 'Good (70+)' },
    beelevenMini: { label: 'Support', h1: 'Need help implementing this plan?', text: 'Beeleven, the agency behind Detekia, can implement the recommendations from this report for you: in-depth audit, technical optimizations, monthly results monitoring.', cta: 'Let\'s talk &rarr;', footer: 'beeleven.fr &middot; hello@detekia.fr' },
    context: { label: '2026 Context' },
    citation: { label: 'AI Visibility Test', h1: 'Consolidated AI Visibility Test', queriesCite: 'queries\ncite your site', cited: 'Cited', notCited: 'Not cited', bestOpp: 'Best opportunity:', mainBlocker: 'Main blocker:', generic: 'Generic', niche: 'Niche', longTail: 'Long tail' },
    patterns: { label: 'Patterns Detected', h1: 'Cross-page Patterns Identified', critique: 'Critical', important: 'Important', mineur: 'Minor', pagesAffected: 'pages affected' },
    actionPlan: { label: 'Site Action Plan', h1: 'Consolidated Priority Actions', colPriority: 'Priority', colAction: 'Action', colCriterion: 'Criterion', colImpact: 'Impact', colEffort: 'Effort', colPages: 'Pages', pagesAffected: 'pages affected' },
    perPage: { label: 'Per-page Detail', errorNote: 'This page could not be analyzed', topRecos: 'Top 3 recommendations' },
    methodology: { label: 'Methodology', h1: 'Analysis Methodology', text: 'This report is generated by automated analysis of each page via a specialized scraping service and evaluation across 8 weighted criteria. The Editorial Neutrality criterion is evaluated by artificial intelligence. The AI visibility test is performed by query simulation. Results vary depending on the AI engine and timing.' },
    beelevenFull: { label: 'Going further', h1: 'Going further with Beeleven', text: 'You have the full diagnosis of your site. Beeleven, the agency that created Detekia, can implement the recommendations for you: in-depth audit, technical optimizations, monthly results monitoring.', cta: 'Let\'s talk &rarr;' },
    email: { subject: 'Your complete Detekia GEO report is ready', headerLabel: 'COMPLETE GEO REPORT — SITE AUDIT', topPriority: 'Top Priority', filename: 'complete-geo-report' },
  },
};

function generateProReportHTML(report, locale = 'fr') {
  const t = T[locale] || T.fr;
  const { rootUrl, scoreAverage, scoreMedian, distribution, pagesValid, pagesWithError,
    executiveSummary, topStrengths, topWeaknesses, patterns, actionPlan,
    citationTestConsolidated, pages, criteriaAverages, consolidatedAt } = report;

  const date = new Date(consolidatedAt || Date.now()).toLocaleDateString(locale === 'en' ? 'en-US' : 'fr-FR', { day: 'numeric', month: 'long', year: 'numeric' });
  const totalPages = pagesValid + (pagesWithError || 0);
  const gradeColor = scoreAverage >= 70 ? '#10A37F' : scoreAverage >= 45 ? '#C9861A' : '#D97757';

  const P = 'page-break-before:always;padding:52px 56px 64px;background:#fff;box-sizing:border-box;';
  const sLabel = (txt, color = '#D97757') => `<div style="font-family:monospace;font-size:10px;color:${color};letter-spacing:3px;text-transform:uppercase;margin-bottom:8px;">${txt}</div>`;
  const H1 = (txt) => `<h1 style="font-family:Georgia,serif;font-size:34px;color:#1A1916;letter-spacing:-1px;margin-bottom:28px;line-height:1.1;">${txt}</h1>`;
  const H2 = (txt) => `<h2 style="font-family:Georgia,serif;font-size:20px;color:#1A1916;margin-bottom:14px;">${txt}</h2>`;

  function severityBadge(sev) {
    const s = String(sev || '').toLowerCase();
    if (s.includes('critique') || s.includes('critical')) return `<span style="display:inline-block;padding:2px 9px;border-radius:10px;font-family:monospace;font-size:9px;background:rgba(217,119,87,0.12);color:#D97757;">${t.patterns.critique}</span>`;
    if (s.includes('important')) return `<span style="display:inline-block;padding:2px 9px;border-radius:10px;font-family:monospace;font-size:9px;background:rgba(201,134,26,0.12);color:#C9861A;">${t.patterns.important}</span>`;
    return `<span style="display:inline-block;padding:2px 9px;border-radius:10px;font-family:monospace;font-size:9px;background:rgba(16,163,127,0.12);color:#10A37F;">${t.patterns.mineur}</span>`;
  }

  function formatPagesList(urls, max = 5) {
    if (!Array.isArray(urls) || urls.length === 0) return '';
    const shown = urls.slice(0, max).map(u => esc(u)).join(', ');
    const extra = urls.length > max ? ` +${urls.length - max}` : '';
    return `<span style="font-family:monospace;font-size:10px;color:#8A8680;">${shown}${extra}</span>`;
  }

  function pageScoreColor(s) { return s >= 70 ? '#10A37F' : s >= 45 ? '#C9861A' : '#D97757'; }

  // ── COVER
  const cover = `
  <div style="background:#1A1916;min-height:100vh;padding:72px 64px;position:relative;overflow:hidden;display:flex;flex-direction:column;justify-content:space-between;box-sizing:border-box;">
    <div style="position:absolute;top:-100px;right:-100px;width:400px;height:400px;border-radius:50%;background:${gradeColor};opacity:0.05;pointer-events:none;"></div>
    <div>
      <div style="display:flex;align-items:center;gap:12px;margin-bottom:12px;">
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:3px;width:20px;height:20px;">
          <div style="background:#10A37F;border-radius:50%;"></div><div style="background:#D97757;border-radius:50%;"></div>
          <div style="background:#4285F4;border-radius:50%;"></div><div style="background:#1C7DC4;border-radius:50%;"></div>
        </div>
        <span style="font-family:Georgia,serif;font-size:18px;color:#F7F5F2;font-weight:bold;">Detekia</span>
      </div>
      <div style="font-family:monospace;font-size:9px;color:rgba(247,245,242,0.35);letter-spacing:3px;text-transform:uppercase;margin-bottom:32px;">${t.cover.title}</div>
      <div style="font-family:monospace;font-size:11px;color:#D97757;letter-spacing:2px;margin-bottom:48px;">${t.cover.subtitle}</div>
      <div style="font-family:Georgia,serif;font-size:72px;color:#F7F5F2;letter-spacing:-3px;line-height:1;">${scoreAverage}</div>
      <div style="font-family:monospace;font-size:14px;color:rgba(247,245,242,0.3);">/100 — ${totalPages} ${t.exec.pagesAnalyzed}</div>
      <div style="margin-top:24px;font-family:monospace;font-size:12px;color:#D97757;">${esc(rootUrl)}</div>
    </div>
    <div>
      <div style="font-family:system-ui;font-size:12px;color:rgba(247,245,242,0.28);">${t.cover.confidential}</div>
      <div style="font-family:system-ui;font-size:11px;color:rgba(247,245,242,0.2);">Beeleven SASU &middot; hello@detekia.fr &middot; detekia.fr</div>
    </div>
  </div>`;

  // ── EXECUTIVE SUMMARY
  const distHTML = `<div style="display:flex;gap:12px;margin-bottom:28px;">
    <div style="flex:1;background:rgba(217,119,87,0.08);border-radius:10px;padding:16px;text-align:center;"><div style="font-family:Georgia,serif;font-size:28px;color:#D97757;">${distribution.faible || 0}</div><div style="font-family:monospace;font-size:9px;color:#8A8680;margin-top:4px;">${t.exec.low}</div></div>
    <div style="flex:1;background:rgba(201,134,26,0.08);border-radius:10px;padding:16px;text-align:center;"><div style="font-family:Georgia,serif;font-size:28px;color:#C9861A;">${distribution.moyen || 0}</div><div style="font-family:monospace;font-size:9px;color:#8A8680;margin-top:4px;">${t.exec.avg}</div></div>
    <div style="flex:1;background:rgba(16,163,127,0.08);border-radius:10px;padding:16px;text-align:center;"><div style="font-family:Georgia,serif;font-size:28px;color:#10A37F;">${distribution.bon || 0}</div><div style="font-family:monospace;font-size:9px;color:#8A8680;margin-top:4px;">${t.exec.good}</div></div>
  </div>`;

  const strengthsHTML = (topStrengths || []).map(s => `<div style="display:flex;gap:8px;margin-bottom:8px;"><span style="color:#10A37F;flex-shrink:0;">&#10003;</span><span style="font-family:system-ui;font-size:13px;color:#1A1916;line-height:1.5;">${esc(s)}</span></div>`).join('');
  const weaknessesHTML = (topWeaknesses || []).map(w => `<div style="display:flex;gap:8px;margin-bottom:8px;"><span style="color:#D97757;flex-shrink:0;">&#10007;</span><span style="font-family:system-ui;font-size:13px;color:#1A1916;line-height:1.5;">${esc(w)}</span></div>`).join('');

  const execSummary = `
  <div style="${P}">
    ${sLabel(t.exec.label)}
    ${H1(t.exec.h1)}
    <div style="display:flex;gap:24px;margin-bottom:28px;">
      <div style="background:#1A1916;border-radius:14px;padding:20px 28px;text-align:center;"><div style="font-family:Georgia,serif;font-size:48px;color:#F7F5F2;letter-spacing:-2px;">${scoreAverage}</div><div style="font-family:monospace;font-size:10px;color:rgba(247,245,242,0.35);">${t.exec.avgScore}</div></div>
      <div style="background:#1A1916;border-radius:14px;padding:20px 28px;text-align:center;"><div style="font-family:Georgia,serif;font-size:48px;color:#F7F5F2;letter-spacing:-2px;">${scoreMedian}</div><div style="font-family:monospace;font-size:10px;color:rgba(247,245,242,0.35);">${t.exec.medianScore}</div></div>
      <div style="background:#1A1916;border-radius:14px;padding:20px 28px;text-align:center;"><div style="font-family:Georgia,serif;font-size:48px;color:${gradeColor};letter-spacing:-2px;">${totalPages}</div><div style="font-family:monospace;font-size:10px;color:rgba(247,245,242,0.35);">${t.exec.pagesAnalyzed}</div></div>
    </div>
    ${H2(t.exec.distribution)}
    ${distHTML}
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-bottom:28px;">
      <div><div style="font-family:monospace;font-size:9px;color:#10A37F;letter-spacing:2px;text-transform:uppercase;margin-bottom:10px;">${t.exec.strengths}</div>${strengthsHTML}</div>
      <div><div style="font-family:monospace;font-size:9px;color:#D97757;letter-spacing:2px;text-transform:uppercase;margin-bottom:10px;">${t.exec.weaknesses}</div>${weaknessesHTML}</div>
    </div>
    ${H2(t.exec.summary)}
    <div style="font-family:system-ui;font-size:13px;color:#1A1916;line-height:1.75;white-space:pre-wrap;">${esc(executiveSummary || '')}</div>
  </div>`;

  // ── BEELEVEN MINI
  const beelevenUrl = locale === 'en' ? 'https://detekia.fr/en/contact' : 'https://detekia.fr/contact';
  const beelevenMini = `
  <div style="${P}display:flex;align-items:center;justify-content:center;padding-top:120px;padding-bottom:120px;">
    <div style="max-width:480px;text-align:center;">
      ${sLabel(t.beelevenMini.label)}
      ${H1(t.beelevenMini.h1)}
      <p style="font-family:system-ui;font-size:14px;color:#6B6762;line-height:1.7;margin-bottom:32px;">${t.beelevenMini.text}</p>
      <a href="${beelevenUrl}" style="display:inline-block;background:#D97757;color:#fff;padding:14px 36px;border-radius:10px;font-family:system-ui;font-size:15px;font-weight:700;text-decoration:none;">${t.beelevenMini.cta}</a>
      <div style="font-family:monospace;font-size:10px;color:#B0ABA5;margin-top:16px;letter-spacing:1px;">${t.beelevenMini.footer}</div>
    </div>
  </div>`;

  // ── CITATION TEST
  const ct = citationTestConsolidated || {};
  const queries = ct.queries || [];
  const citedCount = queries.filter(q => q.cited).length;
  const queryCards = queries.map(q => {
    const typeLabel = q.type === 'generic' ? t.citation.generic : q.type === 'niche' ? t.citation.niche : t.citation.longTail;
    const citedBadge = q.cited
      ? `<span style="display:inline-block;padding:2px 9px;border-radius:10px;font-family:monospace;font-size:9px;background:rgba(16,163,127,0.12);color:#10A37F;">${t.citation.cited}</span>`
      : `<span style="display:inline-block;padding:2px 9px;border-radius:10px;font-family:monospace;font-size:9px;background:rgba(217,119,87,0.12);color:#D97757;">${t.citation.notCited}</span>`;
    return `<div style="background:#FAFAF9;border:1px solid #E5E2DC;border-radius:8px;padding:12px 16px;margin-bottom:8px;">
      <div style="display:flex;align-items:center;gap:8px;margin-bottom:6px;">
        ${citedBadge}
        <span style="font-family:monospace;font-size:9px;color:#8A8680;">${typeLabel}</span>
      </div>
      <div style="font-family:system-ui;font-size:13px;color:#1A1916;margin-bottom:4px;">${esc(q.query)}</div>
      <div style="font-family:system-ui;font-size:11px;color:#8A8680;line-height:1.5;">${esc(q.recommendation || '')}</div>
    </div>`;
  }).join('');

  const citationPage = `
  <div style="${P}">
    ${sLabel(t.citation.label)}
    ${H1(t.citation.h1)}
    <div style="display:flex;gap:20px;margin-bottom:28px;">
      <div style="background:#1A1916;border-radius:14px;padding:20px 28px;text-align:center;"><div style="font-family:Georgia,serif;font-size:42px;color:#F7F5F2;">${citedCount}/${queries.length}</div><div style="font-family:monospace;font-size:10px;color:rgba(247,245,242,0.35);white-space:pre-line;">${t.citation.queriesCite}</div></div>
      <div style="flex:1;">
        <div style="background:#E8F7F3;border-radius:10px;padding:14px 18px;margin-bottom:8px;"><div style="font-family:monospace;font-size:9px;color:#10A37F;margin-bottom:4px;">${t.citation.bestOpp}</div><div style="font-family:system-ui;font-size:12px;color:#1A1916;line-height:1.5;">${esc(ct.bestOpportunity || '')}</div></div>
        <div style="background:rgba(217,119,87,0.06);border-radius:10px;padding:14px 18px;"><div style="font-family:monospace;font-size:9px;color:#D97757;margin-bottom:4px;">${t.citation.mainBlocker}</div><div style="font-family:system-ui;font-size:12px;color:#1A1916;line-height:1.5;">${esc(ct.mainBlocker || '')}</div></div>
      </div>
    </div>
    ${queryCards}
  </div>`;

  // ── PATTERNS
  const patternsCards = (patterns || []).map(p => `
    <div style="background:#FAFAF9;border:1px solid #E5E2DC;border-radius:10px;padding:16px 20px;margin-bottom:10px;page-break-inside:avoid;">
      <div style="display:flex;align-items:center;gap:8px;margin-bottom:8px;">${severityBadge(p.severity)}<span style="font-family:monospace;font-size:10px;color:#8A8680;">${esc(p.criterion || '')}</span></div>
      <div style="font-family:system-ui;font-size:13px;color:#1A1916;line-height:1.6;margin-bottom:8px;">${esc(p.pattern)}</div>
      <div style="font-family:monospace;font-size:10px;color:#8A8680;">${(p.pagesAffected || []).length} ${t.patterns.pagesAffected}</div>
      ${formatPagesList(p.pagesAffected)}
    </div>`).join('');

  const patternsPage = `
  <div style="${P}">
    ${sLabel(t.patterns.label)}
    ${H1(t.patterns.h1)}
    ${patternsCards || '<p style="font-family:system-ui;font-size:13px;color:#8A8680;">Aucun pattern identifie.</p>'}
  </div>`;

  // ── ACTION PLAN
  const actionRows = (actionPlan || []).map((a, i) => {
    const impactColor = (a.impact || '').includes('eleve') || (a.impact || '').includes('high') ? '#D97757' : (a.impact || '').includes('moyen') || (a.impact || '').includes('medium') ? '#C9861A' : '#10A37F';
    return `<div style="background:#FAFAF9;border:1px solid #E5E2DC;border-radius:10px;padding:16px 20px;margin-bottom:8px;page-break-inside:avoid;">
      <div style="display:flex;align-items:center;gap:10px;margin-bottom:8px;">
        <span style="font-family:Georgia,serif;font-size:18px;color:${impactColor};min-width:24px;">${i + 1}</span>
        <span style="font-family:monospace;font-size:9px;color:#8A8680;">${esc(a.criterion || '')}</span>
        <span style="font-family:monospace;font-size:9px;color:${impactColor};margin-left:auto;">${esc(a.impact || '')} &middot; ${esc(a.effort || '')}</span>
      </div>
      <div style="font-family:system-ui;font-size:13px;color:#1A1916;line-height:1.6;margin-bottom:6px;">${esc(a.action)}</div>
      <div style="font-family:monospace;font-size:10px;color:#8A8680;">${(a.pagesAffected || []).length} ${t.actionPlan.pagesAffected}</div>
    </div>`;
  }).join('');

  const actionPlanPage = `
  <div style="${P}">
    ${sLabel(t.actionPlan.label)}
    ${H1(t.actionPlan.h1)}
    ${actionRows || '<p style="font-family:system-ui;font-size:13px;color:#8A8680;">Aucune action identifiee.</p>'}
  </div>`;

  // ── PER-PAGE DETAIL
  const perPageHTML = (pages || []).map((p, idx) => {
    if (p.error) {
      return `<div style="${P}">
        ${sLabel(`${t.perPage.label} — ${idx + 1}/${pages.length}`)}
        <div style="font-family:monospace;font-size:12px;color:#D97757;margin-bottom:8px;">${esc(p.url)}</div>
        <div style="background:rgba(217,119,87,0.06);border:1px solid rgba(217,119,87,0.2);border-radius:10px;padding:20px;font-family:system-ui;font-size:13px;color:#D97757;">${t.perPage.errorNote} : ${esc(p.error)}</div>
      </div>`;
    }
    const sc = pageScoreColor(p.score || 0);
    const recos = (p.recommendations || []).slice(0, 3);
    const recosHTML = recos.map((r, ri) => {
      const rc = r.priority === 'high' ? '#D97757' : r.priority === 'medium' ? '#C9861A' : '#10A37F';
      return `<div style="background:#FAFAF9;border-left:3px solid ${rc};border-radius:0 8px 8px 0;padding:12px 16px;margin-bottom:6px;">
        <div style="display:flex;gap:8px;align-items:center;margin-bottom:4px;">
          <span style="font-family:monospace;font-size:9px;color:${rc};">#${ri + 1}</span>
          <span style="font-family:monospace;font-size:9px;color:#8A8680;">${esc(r.criterion || '')}</span>
        </div>
        <div style="font-family:system-ui;font-size:12px;color:#1A1916;line-height:1.5;">${esc(r.diagnostic || r.title || '')}</div>
        ${r.whatToDo ? `<div style="font-family:system-ui;font-size:11px;color:#8A8680;margin-top:4px;line-height:1.5;">${esc(r.whatToDo)}</div>` : ''}
      </div>`;
    }).join('');

    return `<div style="${P}">
      ${sLabel(`${t.perPage.label} — ${idx + 1}/${pages.length}`)}
      <div style="display:flex;align-items:flex-end;justify-content:space-between;margin-bottom:16px;">
        <div style="font-family:monospace;font-size:12px;color:#D97757;max-width:70%;">${esc(p.url)}</div>
        <div style="text-align:right;"><div style="font-family:Georgia,serif;font-size:36px;color:${sc};line-height:1;">${p.score ?? '?'}<span style="font-size:14px;color:#C0BBB5;">/${p.criteria ? p.criteria.reduce((s, c) => s + (c.max || 0), 0) : 100}</span></div></div>
      </div>
      ${p.topPriority ? `<div style="background:rgba(217,119,87,0.06);border-left:3px solid #D97757;border-radius:0 8px 8px 0;padding:12px 16px;margin-bottom:16px;font-family:system-ui;font-size:12px;color:#1A1916;line-height:1.5;">${esc(p.topPriority)}</div>` : ''}
      ${recos.length > 0 ? `<div style="font-family:monospace;font-size:9px;color:#8A8680;letter-spacing:2px;text-transform:uppercase;margin-bottom:10px;">${t.perPage.topRecos}</div>${recosHTML}` : ''}
    </div>`;
  }).join('');

  // ── METHODOLOGY
  const methodologyPage = `
  <div style="${P}">
    ${sLabel(t.methodology.label)}
    ${H1(t.methodology.h1)}
    <p style="font-family:system-ui;font-size:13px;color:#1A1916;line-height:1.75;">${t.methodology.text}</p>
    <div style="margin-top:28px;font-family:monospace;font-size:10px;color:#B0ABA5;">${t.email.filename} &middot; ${date} &middot; detekia.fr</div>
  </div>`;

  // ── BEELEVEN FULL
  const beelevenFull = `
  <div style="${P}display:flex;align-items:center;justify-content:center;padding-top:120px;padding-bottom:120px;">
    <div style="max-width:480px;text-align:center;">
      ${sLabel(t.beelevenFull.label)}
      ${H1(t.beelevenFull.h1)}
      <p style="font-family:system-ui;font-size:14px;color:#6B6762;line-height:1.7;margin-bottom:32px;">${t.beelevenFull.text}</p>
      <a href="${beelevenUrl}" style="display:inline-block;background:#D97757;color:#fff;padding:14px 36px;border-radius:10px;font-family:system-ui;font-size:15px;font-weight:700;text-decoration:none;">${t.beelevenFull.cta}</a>
      <div style="font-family:monospace;font-size:10px;color:#B0ABA5;margin-top:16px;letter-spacing:1px;">${t.beelevenMini.footer}</div>
    </div>
  </div>`;

  // ── ASSEMBLE
  return `<!DOCTYPE html>
<html lang="${locale}">
<head>
<meta charset="UTF-8">
<title>${t.cover.title} — ${esc(rootUrl)}</title>
<style>
  @page { size: A4; margin: 0; }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  html, body { background: #fff; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  h1, h2, h3 { page-break-after: avoid; break-after: avoid; }
  p { orphans: 3; widows: 3; }
  tr { page-break-inside: avoid; break-inside: avoid; }
</style>
</head>
<body>
${cover}
${execSummary}
${beelevenMini}
${citationPage}
${actionPlanPage}
${patternsPage}
${perPageHTML}
${methodologyPage}
${beelevenFull}
</body>
</html>`;
}

module.exports = { generateProReportHTML, PRO_STRINGS: T };
